language: go
sudo: required
install:
  - go get -v github.com/spf13/hugo
  - sudo pip install --upgrade pip
  - sudo pip install pygments
  - sudo pip install s3cmd
script:
  - hugo
  - s3cmd sync --delete-removed --reduced-redundancy --guess-mime-type --add-header="Cache-Control:max-age=3600" -P -M -r public/ s3://${AWS_BUCKET_NAME}/