# Site settings
title: Bill Glover
email: bill@billglover.co.uk
description: >
  A technology architect with a tendency to tinker
baseurl: ""
url: "http://billglover.me"
twitter_username: billglover
github_username:  billglover
timezone: Europe/London

# Build settings
markdown: kramdown
highlighter: pygments

# Markdown settings
kramdown:
  input: GFM
