languageCode: en-gb
title: Bill Glover
baseurl: 'https://billglover.me/'
theme: wip
paginate: 10
enableRobotsTXT: true
MetaDataFormat: yaml
pygmentsCodefences: true
pygmentsUseClasses: true
pluralizelisttitles: "false"
enableGitInfo: true
permalinks:
  post: '/:year/:month/:day/:title/'

frontmatter:
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate

# Theme parameters
params:
  author: Bill Glover
  displayTitle: false
  description: architecture - code - people
  copyright: "Copyright © 2022 Bill Glover"
  avatar: img/avatar.jpg
  showUpdated: true
  menuOnIndex: false
  mainSections:
    - post
  plausible: https://plausible.billglover.me/js/plausible.js
  relMe:
    mastodon: https://fosstodon.org/@billglover


# Use a menu rather than a generated list of sections to avoid
# odd naming issues with pluralisation.
menu:
  main:
    - name: home
      url: /
      weight: 10
    - name: blog
      url: /post/
      weight: 20
    - name: notes
      url: /notes/
      weight: 30
    - name: videos
      url: /videos/
      weight: 35
    - name: github
      url: https://github.com/billglover
      weight: 40
    - name: contact
      url: /contact/
      weight: 50
  index:
    - name: blog
      url: /post/
      weight: 10
    - name: notes
      url: /notes/
      weight: 20
    - name: videos
      url: /videos/
      weight: 25
    - name: github
      url: https://github.com/billglover
      weight: 30
    - name: contact
      url: /contact/
      weight: 40

social:
  rss-square: /index.xml
  twitter: 'https://www.twitter.com/billglover'
  github: 'https://www.github.com/billglover'
  mastodon: 'https://mastodon.technology/@bill'
  twitch: 'https://www.twitch.tv/billgloveruk'
  linkedin: 'https://www.linkedin.com/in/billgloveruk/'
taxonomies:
  tag: tags
  category: categories
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true
