languageCode = "en-gb"
title = "Bill Glover"
baseurl = "https://billglover.me/"
theme = "cactus"
paginate = 10.0
enableRobotsTXT = true
MetaDataFormat = "yaml"
pygmentsCodefences = true
pygmentsUseClasses = true

[permalinks]
post = "/:year/:month/:day/:title/"

[menu]

  [[menu.main]]
  name = "pgp"
  url = "/pgp/"
  weight = 200.0

[params]
author = "Bill Glover"
description = "architecture - code - people"
socialIconStyle = "circle"
name = "Bill Glover"
bio = "architecture - code - people"
twitter = "BillGlover"

[social]
twitter = "https://www.twitter.com/billglover"
github = "https://www.github.com/billglover"
instagram = "https://www.instagram.com/billglover"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"