languageCode: en-gb
title: Bill Glover
baseurl: 'https://billglover.me/'
theme: wip
paginate: 10
enableRobotsTXT: true
MetaDataFormat: yaml
pygmentsCodefences: true
pygmentsUseClasses: true
pluralizelisttitles: "false"
enableGitInfo: true
timeout: 2m # extended for image processing
permalinks:
  post: '/:year/:month/:day/:title/'

frontmatter:
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate

# Theme parameters
params:
  author:
    name: Bill
    email: hello@bill.dev
  displayTitle: false
  description: geek, photographer, father, love learning
  copyright: "Copyright © 2024 Bill Glover"
  photoLicense: CC BY-NC-ND 4.0
  avatar: img/avatar.jpg
  showUpdated: true
  menuOnIndex: false
  mainSections:
    - post
    - watch
    - travel
  plausible: https://plausible.billglover.me/js/script.js
  webmention:
    baseURL: https://billglover.me
    server: https://webmention.io/api/mentions.jf2
  relMe:
    mastodon: https://hachyderm.io/@bill


# Use a menu rather than a generated list of sections to avoid
# odd naming issues with pluralisation.
menu:
  main:
    - name: home
      url: /
      weight: 10
    - name: blog
      url: /post/
      weight: 20
    - name: notes
      url: /notes/
      weight: 30
    - name: videos
      url: /videos/
      weight: 35
    - name: photos
      url: /photos/
      weight: 36
    - name: now
      url: /now/
      weight: 40
    - name: contact
      url: /contact/
      weight: 50
  index:
    - name: blog
      url: /post/
      weight: 10
    - name: notes
      url: /notes/
      weight: 20
    - name: videos
      url: /videos/
      weight: 25
    - name: photos
      url: /photos/
      weight: 26
    - name: now
      url: /now/
      weight: 30
    - name: contact
      url: /contact/
      weight: 40

social:
  rss-square: /index.xml
  github: 'https://www.github.com/billglover'
  mastodon: 'https://mastodon.technology/@bill'
  linkedin: 'https://www.linkedin.com/in/billgloveruk/'
taxonomies:
  tag: tags
  category: categories
  series: series
markup:
  goldmark:
    renderer:
      unsafe: true

imaging:
  exif:
    disableDate: false
    disableLatLong: true
    excludeFields: ""
    includeFields: ".*"