name = "Bill"
license = "MIT"
licenselink = ""
description = "A modified version of the Cactus theme"
homepage = "https://billglover.me/"
tags = ["blog", "personal"]
features = ["blog"]
min_version = 0.29

[author]
  name = "billglover"
  homepage = "https://billglover.me/"

[original]
  # Customised the Cactus theme
  author = "digitalcraftsman"
  homepage = "https://github.com/digitalcraftsman"
  repo = "https://github.com/digitalcraftsman/hugo-cactus-theme"

[[original]]
  # Ported the stardard theme of the Cactus for Mac static site generator to Jekyll
  name = "Nick Balestra"
  homepage = "http://nick.balestra.ch/"
  repo = "https://github.com/nickbalestra/kactus"

[[original]]
  # Original creators of the stardard theme for the Cactus for Mac static site generator
  name = "Cactus for Mac authors"
  homepage = "http://cactusformac.com"
  repo = "https://github.com/koenbok/Cactus"
  