name: Publish

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: prepare hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    
    - name: build
      run: hugo

    - name: deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        source: "public/"
        strip_components: 1
        target: "/var/www/html/"
