name: Publish

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - master
      - theme
  repository_dispatch:
    types:
      - publish

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: message
      if: github.event.action == 'publish'
      run: |
        echo "'publish' received from '${{ github.event.client_payload.repository }}'"

    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
      
    - name: prepare hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    
    - name: build
      run: hugo -v

    - name: deploy
      if: github.ref == 'refs/heads/master'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        source: "public/"
        strip_components: 1
        target: "/var/www/html/"
