name: Publish Dev

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true
      
    - name: prepare hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    
    - name: build
      run: hugo -v -b "https://dev.billglover.me/" --buildDrafts --buildFuture

    - name: deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        source: "public/"
        strip_components: 1
        target: "/var/www/dev/"
