name: "Update Content"
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-content

jobs:
  update-content:
    name: "Update Content"
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
    
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name '🤖 Content Robot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}/${{ github.repository }}
          git commit -am "📝 New content push" && git push || echo "No changes to commit"
